<a href="https://colab.research.google.com/github/tinypenguin-Bang/Machine-Deep-Learning-HW/blob/main/2021251496_%EB%B0%A9%EC%A3%BC%ED%98%95_%EA%B3%BC%EC%A0%9C_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기초적인 Numpy 활용법
*   numpy import하기
*   np.array()를 통해 리스트를 numpy array로 바꾸기
*   array간 의 간단한 연산하기

In [ ]:
import numpy as np

# list의 numpy array 변경
A = [1,3,5,7,9]
A_arr = np.array(A)
print(A_arr)

# numpy array간 연산
B = [1,5,9,13,17]
B_arr = np.array(B)
multiply = A_arr * B_arr
print(multiply)

[1 3 5 7 9]
[  1  15  45  91 153]


2차 배열 형태 array 활용
*   2D array 요소 불러오기
*   2D array간 연산 및 행렬곱 적용하기

In [ ]:
C = [[1,5,9,13], [2,6,10,14], [3,7,11,15], [4,8,12,16]]
C_arr = np.array(C)
print(C_arr)
print(C_arr[1][3])

D = [[-16,-16,-16,-16], [-16,-16,-16,-16], [-16,-16,-16,-16], [-16,-16,-16,-16]]
D_arr = np.array(D)
E = C_arr + D_arr
print(E)
C @ E

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
14
[[-15 -11  -7  -3]
 [-14 -10  -6  -2]
 [-13  -9  -5  -1]
 [-12  -8  -4   0]]


array([[-358, -246, -134,  -22],
       [-412, -284, -156,  -28],
       [-466, -322, -178,  -34],
       [-520, -360, -200,  -40]])

*   2D array 전치시키기
*   np.linspace(시작, 끝, 개수) 활용하기

In [ ]:
C_arr.transpose()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
E.T

array([[-15, -14, -13, -12],
       [-11, -10,  -9,  -8],
       [ -7,  -6,  -5,  -4],
       [ -3,  -2,  -1,   0]])

In [ ]:
np.linspace(2,16,63)

array([ 2.        ,  2.22580645,  2.4516129 ,  2.67741935,  2.90322581,
        3.12903226,  3.35483871,  3.58064516,  3.80645161,  4.03225806,
        4.25806452,  4.48387097,  4.70967742,  4.93548387,  5.16129032,
        5.38709677,  5.61290323,  5.83870968,  6.06451613,  6.29032258,
        6.51612903,  6.74193548,  6.96774194,  7.19354839,  7.41935484,
        7.64516129,  7.87096774,  8.09677419,  8.32258065,  8.5483871 ,
        8.77419355,  9.        ,  9.22580645,  9.4516129 ,  9.67741935,
        9.90322581, 10.12903226, 10.35483871, 10.58064516, 10.80645161,
       11.03225806, 11.25806452, 11.48387097, 11.70967742, 11.93548387,
       12.16129032, 12.38709677, 12.61290323, 12.83870968, 13.06451613,
       13.29032258, 13.51612903, 13.74193548, 13.96774194, 14.19354839,
       14.41935484, 14.64516129, 14.87096774, 15.09677419, 15.32258065,
       15.5483871 , 15.77419355, 16.        ])

배열 자동 생성
*   random.randint(start, end, size = (row size, column size)) 사용하기
*   rand(row size, column size) 사용하기


In [ ]:
F = np.random.randint(1, 50, size = (3,3))
print(F)

G = np.random.rand(3,3)
print(G)

[[16  7 19]
 [ 2 16 27]
 [ 1 43 20]]
[[0.65912109 0.68368306 0.38895035]
 [0.1589892  0.73274661 0.44583795]
 [0.45914551 0.36472489 0.26184937]]


*   랜덤 행렬 연산하기
*   특정 범위 가져오기

In [ ]:
print(F.sum())  # 합
print(F.min())  # 최소
print(F.max())  # 최대
print(F.mean()) # 평균
print(F.std())  # 표준편차
print(F.var())  # 분산

H = np.random.randint(20, size = 10)
print(H)

151
1
43
16.77777777777778
12.344839477627689
152.39506172839506
[ 1 15  5 10  7  7 14  6 12 18]


In [ ]:
print(H[:3])  # 처음
print(H[3:])  # 끝
print(H[4:7]) # 중간
print(H[:])   # 전체

[ 1 15  5]
[10  7  7 14  6 12 18]
[ 7  7 14]
[ 1 15  5 10  7  7 14  6 12 18]


Numpy 형태변환
*   차원 확인(.shape), 차원 추가(.expand_dims(a,b)), 차원 삭제(.squeeze(a))
*   형태 변경(.reshape()), 순서 변경(.transpose())

In [ ]:
I = np.random.randint(0, 63, (2,2,10))
print(I.shape)
print(I)

J = np.expand_dims(I,3)
print(J.shape)
K = np.expand_dims(I,1)
print(K.shape)
L = np.squeeze(J,3)  # squeeze 적용 시 다른 위치는 제거가 불가능하기에, 알아보니 보통 shape가 1인 것만 제거가 가능했습니다.
print(L.shape)

(2, 2, 10)
[[[12 25 10  7 59 34  3 38  8 28]
  [46 39 43 56 35 41 33 47 34 48]]

 [[ 0 32 59  3 12 19 61  8 29 48]
  [30 49 18 38  3  7 17 50 29 46]]]
(2, 2, 10, 1)
(2, 1, 2, 10)
(2, 2, 10)


In [ ]:
M = np.arange(60)
print(M.shape)
N = M.reshape(2,3,10)
print(N.shape)

O = N.transpose(2,1,0)
print(O.shape)

(60,)
(2, 3, 10)
(10, 3, 2)


# 기초적인 Pandas 활용법
*   pandas import하기
*   Series(1차원 배열) 활용하기
*   Dictionary에서 만들어 인덱스 넣기

In [ ]:
import pandas as pd

AA = pd.Series([60, 35, 87, 100, 98, 54])
print(type(AA))
print(AA)

BB = pd.Series({'A+':95, 'A':80, 'B+':65, 'B':50, 'C+':35, 'C':15})
print(BB)

<class 'pandas.core.series.Series'>
0     60
1     35
2     87
3    100
4     98
5     54
dtype: int64
A+    95
A     80
B+    65
B     50
C+    35
C     15
dtype: int64


DataFrame(2차원 배열)
*   행의 이름과 열의 이름 적용


In [ ]:
CC = [{'체력':  100, '공격력':  300, '방어력':  200}, 
      {'체력':  500, '공격력':  100, '방어력':  300}, 
      {'체력':  50, '공격력':  500, '방어력':  150}]
CC_df = pd.DataFrame(CC)  #  대소문자 구별 숙지!!!
print(CC_df)

    체력  공격력  방어력
0  100  300  200
1  500  100  300
2   50  500  150


colab 저장 확인

In [ ]:
!ls   # 현재 폴더 파일 확인

sample_data


In [ ]:
!pwd  # 현재 경로 확인

/content


Pandas 데이터 읽기
*   구글 드라이브 연동하기
*   read_csv() 함수로 외부 csv or txt 파일 데이터 읽기

In [ ]:
from google.colab import drive
drive.mount('/g') 

Drive already mounted at /g; to attempt to forcibly remount, call drive.mount("/g", force_remount=True).


In [ ]:
!ls /g

MyDrive


In [ ]:
!ls '/g/MyDrive'

'제목없는 폴더'
'가두모집 시간표 (1).gdoc'
'가두모집 시간표 (2).gdoc'
'가두모집 시간표 (3).gdoc'
'가두모집 시간표 (4).gdoc'
'가두모집 시간표 (5).gdoc'
'Adventure Design 1 (기계융합1) 소홍윤 교수님 조 편성.gsheet'
'Adventure Design 1 (기계융합1) 소홍윤 교수님 기말평가.gsheet'
'Adventure Design 1 (기계융합1) 소홍윤 교수님 중간평가.gsheet'
 ClevMoney
'Colab Notebooks'
'가두모집 시간표.gdoc'
'제목 없는 설문지.gform'


In [ ]:
!ls '/g/MyDrive/Colab Notebooks'

'2021251496 방주형 과제 1-2.ipynb'   report.txt


In [ ]:
data = pd.read_csv('/g/MyDrive/Colab Notebooks/report.txt', sep = '\t')

In [ ]:
data

컬럼1  2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7  \
0                컬럼1   서울시     성별     성별    연령별    연령별    연령별    연령별    연령별   
1                컬럼1   서울시     남자     여자    10대    20대    30대    40대    50대   
2  운동을 할 충분한 시간이 없어서  46.8   52.4   42.5   55.3     46   59.9   54.1   46.1   
3   함께 운동을 할 사람이 없어서     5    4.4    5.6    4.8    4.2    5.2    3.9    6.2   
4   운동을 할 만한 장소가 없어서   4.3    4.9    3.9    3.9    4.5    2.9    2.9    4.5   
5           운동을 싫어해서  37.3   32.4     41   32.6   38.8   27.3   35.5   36.8   
6  운동을 할 충분한 비용이 없어서   5.2    4.9    5.4    3.5    6.4    4.5    3.3    5.6   
7                 기타   1.4    1.1    1.7      -    0.1    0.2    0.4    0.8   

   2019.8  ... 2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48  \
0     연령별  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
1  60대 이상  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
2    26.6  ...    38.5    45.3    53.6    50.2    39.1    44.4    49.9   
3       6  ...     3.8     5.7     2.4     6.7    13.9     8.8     4.3   
4     6.6  ...     1.9     5.8     2.3     3.8     8.4     5.5     4.1   
5    48.7  ...    50.5      39    37.6    33.9    31.1    34.2    36.6   
6     6.6  ...     4.3     2.9     2.3     5.4     7.6     6.1     3.3   
7     5.6  ...       1     1.3     1.7       -       -       1     1.8   

  2019.49 2019.50 2019.51  
0     강남구     송파구     강동구  
1     강남구     송파구     강동구  
2    40.7    47.6      47  
3     4.2       5     5.2  
4       2     2.3     4.8  
5    46.4    39.4    32.4  
6     5.2     4.8     8.4  
7     1.6       1     2.3  

[8 rows x 53 columns]

In [ ]:
data.head(5)

컬럼1  2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7  \
0                컬럼1   서울시     성별     성별    연령별    연령별    연령별    연령별    연령별   
1                컬럼1   서울시     남자     여자    10대    20대    30대    40대    50대   
2  운동을 할 충분한 시간이 없어서  46.8   52.4   42.5   55.3     46   59.9   54.1   46.1   
3   함께 운동을 할 사람이 없어서     5    4.4    5.6    4.8    4.2    5.2    3.9    6.2   
4   운동을 할 만한 장소가 없어서   4.3    4.9    3.9    3.9    4.5    2.9    2.9    4.5   

   2019.8  ... 2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48  \
0     연령별  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
1  60대 이상  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
2    26.6  ...    38.5    45.3    53.6    50.2    39.1    44.4    49.9   
3       6  ...     3.8     5.7     2.4     6.7    13.9     8.8     4.3   
4     6.6  ...     1.9     5.8     2.3     3.8     8.4     5.5     4.1   

  2019.49 2019.50 2019.51  
0     강남구     송파구     강동구  
1     강남구     송파구     강동구  
2    40.7    47.6      47  
3     4.2       5     5.2  
4       2     2.3     4.8  

[5 rows x 53 columns]

In [ ]:
data.tail(5)

컬럼1  2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7  \
3   함께 운동을 할 사람이 없어서     5    4.4    5.6    4.8    4.2    5.2    3.9    6.2   
4   운동을 할 만한 장소가 없어서   4.3    4.9    3.9    3.9    4.5    2.9    2.9    4.5   
5           운동을 싫어해서  37.3   32.4     41   32.6   38.8   27.3   35.5   36.8   
6  운동을 할 충분한 비용이 없어서   5.2    4.9    5.4    3.5    6.4    4.5    3.3    5.6   
7                 기타   1.4    1.1    1.7      -    0.1    0.2    0.4    0.8   

  2019.8  ... 2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48 2019.49  \
3      6  ...     3.8     5.7     2.4     6.7    13.9     8.8     4.3     4.2   
4    6.6  ...     1.9     5.8     2.3     3.8     8.4     5.5     4.1       2   
5   48.7  ...    50.5      39    37.6    33.9    31.1    34.2    36.6    46.4   
6    6.6  ...     4.3     2.9     2.3     5.4     7.6     6.1     3.3     5.2   
7    5.6  ...       1     1.3     1.7       -       -       1     1.8     1.6   

  2019.50 2019.51  
3       5     5.2  
4     2.3     4.8  
5    39.4    32.4  
6     4.8     8.4  
7       1     2.3  

[5 rows x 53 columns]

In [ ]:
data.head()

컬럼1  2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7  \
0                컬럼1   서울시     성별     성별    연령별    연령별    연령별    연령별    연령별   
1                컬럼1   서울시     남자     여자    10대    20대    30대    40대    50대   
2  운동을 할 충분한 시간이 없어서  46.8   52.4   42.5   55.3     46   59.9   54.1   46.1   
3   함께 운동을 할 사람이 없어서     5    4.4    5.6    4.8    4.2    5.2    3.9    6.2   
4   운동을 할 만한 장소가 없어서   4.3    4.9    3.9    3.9    4.5    2.9    2.9    4.5   

   2019.8  ... 2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48  \
0     연령별  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
1  60대 이상  ...     강서구     구로구     금천구    영등포구     동작구     관악구     서초구   
2    26.6  ...    38.5    45.3    53.6    50.2    39.1    44.4    49.9   
3       6  ...     3.8     5.7     2.4     6.7    13.9     8.8     4.3   
4     6.6  ...     1.9     5.8     2.3     3.8     8.4     5.5     4.1   

  2019.49 2019.50 2019.51  
0     강남구     송파구     강동구  
1     강남구     송파구     강동구  
2    40.7    47.6      47  
3     4.2       5     5.2  
4       2     2.3     4.8  

[5 rows x 53 columns]

In [ ]:
data[3:6]

컬럼1  2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7  \
3  함께 운동을 할 사람이 없어서     5    4.4    5.6    4.8    4.2    5.2    3.9    6.2   
4  운동을 할 만한 장소가 없어서   4.3    4.9    3.9    3.9    4.5    2.9    2.9    4.5   
5          운동을 싫어해서  37.3   32.4     41   32.6   38.8   27.3   35.5   36.8   

  2019.8  ... 2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48 2019.49  \
3      6  ...     3.8     5.7     2.4     6.7    13.9     8.8     4.3     4.2   
4    6.6  ...     1.9     5.8     2.3     3.8     8.4     5.5     4.1       2   
5   48.7  ...    50.5      39    37.6    33.9    31.1    34.2    36.6    46.4   

  2019.50 2019.51  
3       5     5.2  
4     2.3     4.8  
5    39.4    32.4  

[3 rows x 53 columns]

In [ ]:
data.describe()

컬럼1 2019 2019.1 2019.2 2019.3 2019.4 2019.5 2019.6 2019.7 2019.8  ...  \
count     8    8      8      8      8      8      8      8      8      8  ...   
unique    7    7      7      8      8      8      8      8      8      7  ...   
top     컬럼1  서울시    4.9     성별    연령별    연령별    연령별    연령별    연령별    6.6  ...   
freq      2    2      2      1      1      1      1      1      1      2  ...   

       2019.42 2019.43 2019.44 2019.45 2019.46 2019.47 2019.48 2019.49  \
count        8       8       8       8       8       8       8       8   
unique       7       7       6       7       7       7       7       7   
top        강서구     구로구     금천구    영등포구     동작구     관악구     서초구     강남구   
freq         2       2       2       2       2       2       2       2   

       2019.50 2019.51  
count        8       8  
unique       7       7  
top        송파구     강동구  
freq         2       2  

[4 rows x 53 columns]

In [ ]:
data.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


Series([], dtype: float64)

In [ ]:
data.dtypes

컬럼1        object
2019       object
2019.1     object
2019.2     object
2019.3     object
2019.4     object
2019.5     object
2019.6     object
2019.7     object
2019.8     object
2019.9     object
2019.10    object
2019.11    object
2019.12    object
2019.13    object
2019.14    object
2019.15    object
2019.16    object
2019.17    object
2019.18    object
2019.19    object
2019.20    object
2019.21    object
2019.22    object
2019.23    object
2019.24    object
2019.25    object
2019.26    object
2019.27    object
2019.28    object
2019.29    object
2019.30    object
2019.31    object
2019.32    object
2019.33    object
2019.34    object
2019.35    object
2019.36    object
2019.37    object
2019.38    object
2019.39    object
2019.40    object
2019.41    object
2019.42    object
2019.43    object
2019.44    object
2019.45    object
2019.46    object
2019.47    object
2019.48    object
2019.49    object
2019.50    object
2019.51    object
dtype: object